import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "@/components/Header";
import BootstrapClient from "@/scripts/BootstrapClient";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import {CartProvider} from "@/context/CartContext";
import {AuthContextProvider} from "@/context/AuthContext";
import { Analytics } from '@vercel/analytics/next';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <BootstrapClient></BootstrapClient>
      <AuthContextProvider>
          <CartProvider>
              <Header></Header>
              <main>
                  {children}
              </main>
          </CartProvider>
      </AuthContextProvider>
      <Analytics></Analytics>
      </body>
    </html>
  );
}
